# Generated by Django 5.2.7 on 2026-01-19 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_later', models.BooleanField(default=False)),
                ('watched', models.BooleanField(default=False)),
                ('mediaitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
