# Generated by Django 5.2.7 on 2026-01-20 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('positive', 'Положительная'), ('neutral', 'Нейтральная'), ('negative', 'Отрицательная')], default='positive', max_length=40)),
                ('rating', models.ImageField(upload_to='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('mediaitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
