# Generated by Django 5.2.7 on 2026-01-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mediaitem_content_type'),
        ('interactions', '0004_alter_review_mediaitem_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediastatus',
            name='mediaitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermediastatus', to='catalog.mediaitem'),
        ),
    ]
