# Generated by Django 5.2.7 on 2026-01-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mediaitem_content_type'),
        ('interactions', '0005_alter_usermediastatus_mediaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mediaitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalog.mediaitem'),
        ),
    ]
