# Generated by Django 5.2.7 on 2026-01-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_genre_slug'),
        ('interactions', '0006_alter_review_mediaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mediaitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.mediaitem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
