# Generated by Django 5.2.7 on 2026-01-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_review_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='type',
        ),
    ]
