# Generated by Django 5.2.7 on 2026-01-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_genre_slug'),
        ('interactions', '0010_remove_review_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermediastatus',
            options={'verbose_name': 'Статус контента пользователя', 'verbose_name_plural': 'Статусы контента пользователей'},
        ),
        migrations.RemoveField(
            model_name='usermediastatus',
            name='watch_later',
        ),
        migrations.RemoveField(
            model_name='usermediastatus',
            name='watched',
        ),
        migrations.AddField(
            model_name='usermediastatus',
            name='status',
            field=models.CharField(choices=[('none', 'Без статуса'), ('watch_later', 'Смотреть позже'), ('watched', 'Просмотрено')], default='none', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Настроение рецензии'),
        ),
        migrations.AlterField(
            model_name='usermediastatus',
            name='mediaitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermediastatus', to='catalog.mediaitem', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='usermediastatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
