# Generated by Django 5.2.7 on 2026-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_alter_usermediastatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediastatus',
            name='status',
            field=models.CharField(choices=[(None, 'Без статуса'), ('watch_later', 'Смотреть позже'), ('watched', 'Просмотрено')], default=None, max_length=20, verbose_name='Статус'),
        ),
    ]
