# Generated by Django 5.2.7 on 2026-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0012_alter_usermediastatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediastatus',
            name='status',
            field=models.CharField(choices=[('Без статуса', 'None'), ('Смотреть позже', 'Watch Later'), ('Просмотрено', 'Watched')], default='Без статуса', max_length=20, verbose_name='Статус'),
        ),
    ]
