# Generated by Django 5.2.7 on 2026-01-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_alter_usermediastatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediastatus',
            name='status',
            field=models.CharField(choices=[('none', 'Без статуса'), ('watch_later', 'Смотреть позже'), ('watched', 'Просмотрено')], default='none', max_length=20, verbose_name='Статус'),
        ),
    ]
