# Generated by Django 5.2.7 on 2026-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_alter_usermediastatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediastatus',
            name='status',
            field=models.CharField(choices=[('none', 'Без статуса'), ('planned', 'Запланировано'), ('completed', 'Завершено')], default='none', max_length=20, verbose_name='Статус'),
        ),
    ]
