# Generated by Django 5.2.7 on 2026-02-11 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0015_alter_usermediastatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Положительная'), ('neutral', 'Нейтральная'), ('negative', 'Отрицательная')], max_length=20, verbose_name='Настроение рецензии'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название статьи'),
        ),
    ]
