# Generated by Django 5.2.7 on 2026-01-19 14:01

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2025)])),
                ('description', models.TextField(blank=True, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('poster', models.ImageField(blank=True, default='catalog/placeholder.jpg', null=True, upload_to=catalog.models.user_directory_path)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('page_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('director', 'Директор'), ('author', 'Автор'), ('studio', 'Студия')], default='director', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.mediaitem')),
            ],
            bases=('catalog.mediaitem',),
        ),
        migrations.CreateModel(
            name='ComputerGame',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.mediaitem')),
                ('budget', models.PositiveIntegerField(null=True)),
            ],
            bases=('catalog.mediaitem',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.mediaitem')),
                ('budget', models.PositiveIntegerField(null=True)),
            ],
            bases=('catalog.mediaitem',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('mediaitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.mediaitem')),
            ],
            bases=('catalog.mediaitem',),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.creator'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='genres',
            field=models.ManyToManyField(blank=True, to='catalog.genre'),
        ),
    ]
