# Generated by Django 5.2.7 on 2026-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='content_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
