# Generated by Django 5.2.7 on 2026-01-27 08:55

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mediaitem_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='poster',
            field=models.ImageField(blank=True, default='default_content.png', null=True, upload_to=catalog.models.user_directory_path),
        ),
    ]
