# Generated by Django 5.2.7 on 2026-01-28 11:00

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_mediaitem_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='computergame',
            options={'verbose_name': 'Компьютерная игра', 'verbose_name_plural': 'Компьютерные игры'},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'Создатель', 'verbose_name_plural': 'Создатели'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.AddField(
            model_name='genre',
            name='content_type',
            field=models.CharField(blank=True, choices=[('movie', 'Фильм'), ('game', 'Игра'), ('book', 'Книга')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='content_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.creator', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='genres',
            field=models.ManyToManyField(blank=True, to='catalog.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='page_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='poster',
            field=models.ImageField(blank=True, default='default_content.png', null=True, upload_to=catalog.models.user_directory_path, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2025)], verbose_name='Год'),
        ),
    ]
